apt-get install openssl ca-certificate -y
echo "mkdir -p /etc/pki/CA"
echo "mkdir -p /etc/pki/CA/private"
echo "mkdir -p /etc/pki/CA/certs"
echo "mkdir -p /etc/pki/CA/newcerts"
echo "mkdir -p /etc/pki/CA/crl"
echo "touch /etc/pki/CA/index.txt"
echo "echo 1000 > /etc/pki/CA/serial"
echo "chmod 700 /etc/pki/CA/private"
echo "mkdir -p /etc/ssl"